### ISSUE TITLE
Çalışmak lazım

### ISSUE THREAD

**Issue by tahsin-emre** [yumakp/deneme#1]
Biraz azim ve gayretle mvvm bilmese de iyi bir flutter developer çıkar

**Comment by yumakp** [comment]
eyvallah kardeeeeeeeeeeeeeş

________________________________
Gönderen: Tahsin Emre ***@***.***>
Gönderildi: 5 Temmuz 2022 Salı 20:42
Kime: yumakp/deneme ***@***.***>
Bilgi: Subscribed ***@***.***>
Konu: [yumakp/deneme] Çalışmak lazım (Issue #1)


Biraz azim ve gayretle mvvm bilmese de iyi bir flutter developer çıkar
